- title: '仪表盘'
  uri: '/dashboard'
  icon: 'feather icon-bar-chart-2'
  order: '100'
  show: '1'
  children: []

- title: '系统权限'
  uri: ''
  icon: 'feather icon-settings'
  order: '100'
  show: '1'
  extension: ''
  children: 
    - title: '管理员'
      uri: '/auth/admins'
      icon: ''
      order: '100'
      show: '1'
      extension: ''
      children: []
    - title: '角色'
      uri: '/auth/roles'
      icon: ''
      order: '100'
      show: '1'
      extension: ''
      children: []
    - title: '权限'
      uri: '/auth/permissions'
      icon: ''
      order: '100'
      show: '1'
      extension: ''
      children: []
    - title: '菜单'
      uri: '/auth/menus'
      icon: ''
      order: '100'
      show: '1'
      extension: ''
      children: []
    - title: '扩展'
      uri: '/auth/extensions'
      icon: ''
      order: '100'
      show: '1'
      extension: ''
      children: []
